feat - crud ficha
joaomarcelo09/FichaAcad pull request #1
Opened 2024-03-08 18:32 UTC by juliaam

Todas as operações feitas: create, update, delete, findall e findone.

2024-03-09 21:27 UTC, joaomarcelo09 commented on src/modules/ficha/entities/ficha.controller.ts
> +  update(@Param('id') id: string, @Body() updateFichaDto: UpdateFichaDto) {
esta sem o async await

2024-03-09 21:27 UTC, joaomarcelo09 commented on src/modules/ficha/entities/ficha.controller.ts
> +  remove(@Param('id') id: string) {
esta sem o async await

2024-03-09 21:27 UTC, joaomarcelo09 commented on src/modules/ficha/entities/ficha.controller.ts
> +  create(@Body() createFichaDto: CreateFichaDto) {
esta sem o async await

2024-03-09 21:27 UTC, joaomarcelo09 commented on src/modules/atleta/atleta.service.ts
> +      // include
apagar o comentado

2024-03-09 21:27 UTC, joaomarcelo09 commented on src/modules/atleta/atleta.module.ts
> +import { FichaServiceA as FichaService } from 'src/services/ficha/ficha.service';
apagar o ficha service que nao esta sendo utilizado

2024-03-09 21:27 UTC, joaomarcelo09 commented on src/modules/atleta/atleta.controller.ts
> +      // await this.ficha.create(ficha, atleta)
apagar o comentado

2024-03-09 21:27 UTC, joaomarcelo09 commented on src/modules/atleta/atleta.controller.ts
> +    // const {nome, exercicios, intensidade} = await this.ficha.create(ficha, findAtleta)
apagar o comentado

2024-03-09 21:27 UTC, joaomarcelo09 commented on src/modules/ficha/entities/ficha.service.ts
> +      if (!fichasAtleta) {
validaçoes sao feitas no controller, utilizar service apenas para conexao com o banco, nao é preciso colocar o findmany na transaction, sobe as validaçoes para o controller e utilizar o service de findAll para fazer esses finds

2024-03-12 15:04 UTC, juliaam commented on src/modules/ficha/entities/ficha.controller.ts
> +  create(@Body() createFichaDto: CreateFichaDto) {
colocado async e await

2024-03-12 15:05 UTC, juliaam commented on src/modules/ficha/entities/ficha.controller.ts
> +  update(@Param('id') id: string, @Body() updateFichaDto: UpdateFichaDto) {
colocado async e await

2024-03-12 15:05 UTC, juliaam commented on src/modules/ficha/entities/ficha.controller.ts
> +  remove(@Param('id') id: string) {
colocado async e await

2024-03-12 15:08 UTC, juliaam commented on src/modules/atleta/atleta.service.ts
> +      // include
apagar o comentário ou o comentado mesmo?

2024-03-12 15:12 UTC, juliaam commented on src/modules/atleta/atleta.module.ts
> +import { FichaServiceA as FichaService } from 'src/services/ficha/ficha.service';
apagado

2024-03-12 15:14 UTC, juliaam commented on src/modules/atleta/atleta.controller.ts
> +      // await this.ficha.create(ficha, atleta)
apagado

2024-03-12 22:54 UTC, juliaam commented on src/modules/ficha/entities/ficha.service.ts
> +      if (!fichasAtleta) {
corrigido

2024-03-25 18:43 UTC, joaomarcelo09 requested changes

2024-03-25 18:43 UTC, joaomarcelo09 commented on src/modules/atleta/atleta.controller.ts
> +    // const ficha = await criarFicha(tipo, atleta.biotipo)
codigo comentado duplicado

2024-03-25 18:43 UTC, joaomarcelo09 commented on src/modules/atleta/atleta.service.ts
> +      // include
o codigo que estiver comentado é para apagar, todos que nao estao sendo utilizados, se nao daqui a pouco vai ficar com um monte de codigo comentado que a gente n sabe pra que serve

2024-03-25 18:43 UTC, joaomarcelo09 commented on src/services/ficha/ficha.service.ts
apagar o ficha service comentado

2024-03-25 18:43 UTC, joaomarcelo09 commented on src/modules/ficha/ficha.service.ts
> +      if (fichaInfo.ficha_exercicio) {
excesso de request

2024-03-25 18:43 UTC, joaomarcelo09 requested changes
modificaçoes nescessarias

2024-03-27 16:18 UTC, juliaam commented on src/modules/ficha/ficha.service.ts
> +      if (fichaInfo.ficha_exercicio) {
alterado

2024-03-27 18:31 UTC, joaomarcelo09 approved these changes

2024-03-27 21:51 UTC, merged