ATLETA - Nova regra de ficha/atleta
joaomarcelo09/FichaAcad pull request #2
Opened 2024-03-21 14:26 UTC by juliaam

2024-03-25 22:08 UTC, joaomarcelo09 commented on src/modules/atleta/atleta.controller.ts
> +    let ficha: null | FichaType = null;
seria interessante colocar como const ja que nao ha nova atribuiçao de valor

2024-03-25 22:15 UTC, joaomarcelo09 requested changes
comentario no pr

2024-03-27 00:43 UTC, juliaam commented on src/modules/atleta/atleta.controller.ts
> +    let ficha: null | FichaType = null;
alterado

2024-03-27 16:26 UTC, joaomarcelo09 approved these changes

2024-03-27 16:26 UTC, joaomarcelo09 approved these changes

2024-03-27 16:27 UTC, joaomarcelo09 approved these changes

2024-03-27 16:29 UTC, merged